select*
from my_data;

#Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as Total_Revenue
from my_data
group by gender
order by sum(purchase_amount) desc ;

#Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount
from my_data
where discount_applied="Yes" and purchase_amount > (select avg(purchase_amount) from my_data );

select avg(purchase_amount) from my_data ; # avg was 59.76

#Q3. Which are the top 5 products with the highest average review rating?

select item_purchased,round(avg(review_rating),2) as 'Average Product Rating'
from my_data
group by item_purchased
order by avg(review_rating) desc limit 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, round(avg(purchase_amount),2) as 'Average purchase amount'
from my_data	
where shipping_type in ('Standard','Express')
group by shipping_type;

#5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status, count(customer_id) as 'Total Customers', round(avg(purchase_amount),2) as 'Average Spend',
round(sum(purchase_amount),2) as 'Total Revenue'
from my_data
group by subscription_status
order by round(sum(purchase_amount),2);

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
round(100*avg(case when discount_applied='Yes' then 1 else 0 end),2) as Discount_rate
from my_data
group by item_purchased
order by Discount_rate desc limit 5;

#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
# and show the count of each segment. 

with customer_type as(
select customer_id,previous_purchases,
case 
	when previous_purchases =1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from my_data    
)    
select customer_segment, count(*) as 'Number of Customers'
from customer_type
group by customer_segment;

#8 What are the top 3 most purchased products within each category? 

with item_count as (
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from my_data
group by category,item_purchased)

select item_rank,category,item_purchased,total_orders
from item_count
where item_rank <=3;

#9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as Repeat_buyers
from my_data 
where previous_purchases >5
group by subscription_status;

#10  What is the revenue contribution of each age group? 

select age_group,sum(purchase_amount) as Revenue_Contribution 
from my_data
group by age_group
order by sum(purchase_amount) desc;